### PR TITLE
Refactor playbooks as roles to allow for multi server setup in the future

### PR DESCRIPTION
**Pull request by dcmcand**
This PR refactors existing playbooks into roles to allow for a more modular approach to building the server. playbook.yml functions just as before, so it won't break a single server install or a vagrant install.

### CODE REVIEW

**Comment by ghukill** [comment]
Deferring to @colehudson for testing and merging, but at first glance, looks awesome, thanks for putting in the work here.

**Comment by colehudson** [comment]
@dcmcand thank you for the PR! I will be out of town for a conference for the rest of this week. However, I will take a look at this first thing next week.

**Comment by colehudson** [comment]
First, overall looks great and thank you for doing this! Tested to confirm it doesn't break single server or vagrant installs. I did notice a slight typo in the `ip_address` variable found in `group_vars/all.yml` -- an extra colon at the end of the line.

Speaking a bit with @ghukill here has made it more apparent that the next steps will be to look at what tweaks need to be added to equally support all 3 deployment methods....mostly in the area of variable setting/modification in conf files to allow for communication between different servers as well as updating documentation to support a multi-server deployment.

Moving forward, I'll definitely pull these changes in now, and I'll make the change to fix the typo in group_vars. I'm less worried about the to-do list for the multi-server build, as it is and will be an ongoing process and hasn't placed any burdens on or regressed the current deployment methods. All in all, we look forward to seeing how this moves forward!

Cole

**Comment by dcmcand** [comment]
Hi Cole,
Thanks for the merge. So next I was going to look at moving localsettings.py to a ansible template, as discussed in issue #22. Would this be helpful? Or should I hold off until you and @ghukill figure out what tweaks you wish to make.
Regards
Chuck

**Comment by ghukill** [comment]
If I were to weigh in, seems like making `localsettings.py` an Ansible template would still be a good thing.  Wondering, if it might become a model for other configuration files.  

One of the things we discussed was -- if the servers are distinct -- where the hostnames would live for each, as it would inform not only networking considerations, but lots of configurations on the machines (er, mostly the Django app machine).  Circling back, wondered if `localsettings.py` might be a place where all these configurations could live.  

I hestitate to even suggest it, but perhaps a more language agnostic configuration file would be better?  If `localsettings.py` were a `.conf`, `.yml`, or `.json` file at `/home/combine`, it could be readily read by the Combine Django app, and others.  Just thinking out loud here...

**Comment by colehudson** [comment]
Sorry, this got away from me today, @dcmcand. Making the localsettings file into a template makes sense, so please do that if you have time/inclination.

**Pull request merged**
